## Generate by ttconfig ##

THEDIR = platform
FRAMEDIR = platform

include /home/henry/octopuslink/quantum/x86/config.status
include /home/henry/octopuslink/quantum/x86/platform/mk.inf
include $(TOPDIR)/rules.mak
-include /home/henry/octopuslink/quantum/x86/platform/.depend
